- hosts: all
  user: vagrant
  sudo: true

  tasks:
    - name: Install packages
      apt: name={{ item }} state=present
      with_items:
        - build-essential
        - git

    - include: tasks/mongodb.yml
    - include: tasks/nodejs.yml

